FoodRecipes/Controllers/RecipeController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.WebPages;
using DotNetOpenAuth.Messaging;
using FoodRecipes.Filters;
using FoodRecipes.Models;
using log4net;
using System.Diagnostics;
using FoodRecipes.ProjectClasses;
using WebMatrix.WebData;


namespace FoodRecipes.Controllers
{
    
    [AllowAnonymous]
     [LogginActionFilter.LoggingActionFilter]
    public class RecipeController : Controller
    {
        //
        // GET: /Recipe/
        // private static readonly ILog _log = log4net.LogManager.GetLogger(typeof(Controller));
        public ActionResult Index()
        {
            
            return View();
        }
        [Authorize]
        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }
         [Authorize]
        [HttpPost]
        public ActionResult Create(Models.Recipe tempRecipe, HttpPostedFileBase file)
        {
            
            if (file != null && file.ContentLength > 0 && file.ContentType.StartsWith("image/"))
            {
                try
                {

                    string temppath = Guid.NewGuid() + Path.GetExtension(file.FileName);
                    string path = Path.Combine(Server.MapPath("~/Images/siteimg"), temppath);
                    int i;
                    file.SaveAs(path);
                    ViewBag.Message = "File uploaded successfully";
                    tempRecipe.ImgPath = Path.Combine("~/Images/siteimg", temppath);
                }
                catch (Exception ex)
                {
                    ViewBag.Message = "ERROR:" + ex.Message.ToString();
                }
            }
            else
            {
                ModelState.AddModelError("file", "You have not specified a file // wrong file type");
               
            }
            var context = new UsersContext();
            var username = User.Identity.Name;
            var user = context.UserProfiles.SingleOrDefault(u => u.UserName == username);

             tempRecipe.UserId =user.UserId ;
            tempRecipe.TimeStamp = DateTime.Now;
            tempRecipe.FinalRate = 0;
            tempRecipe.RatingPeople = 0;
            if (ModelState.IsValid)
            {
                var db = new RecipeDataContext();

                db.Recipes.Add(tempRecipe);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(tempRecipe);
        }
        [HttpGet]
        public ActionResult Search()
        {
            var initgroupsize = 6;

            var groupnumberlist = new SelectList(new[] { "6","12", "24" });
            ViewBag.GroupNumberList = groupnumberlist;
            
            var searchlist = new SelectList(new[] { "Title","Food Rate", "people number" });
            ViewBag.SearchList = searchlist;
            var db = new RecipeDataContext();
            SearchCal searchCal=new SearchCal(db);
             var groupnumber=searchCal.SearchGropNumber(initgroupsize);
          //  IQueryable<Recipe> recipelist = db.Recipes;
            var recipelist1 = new List<Recipe>();
            if (db.Recipes.Count() != 0)
            {
   
                if (db.Recipes.Count()<=initgroupsize)
                {
                     recipelist1 = db.Recipes.ToList();
                }
                else
                {
                  //  var idtemp = searchCal.IdStartPoint(groupnumber,initgroupsize);
             
                   //recipelist = recipelist1.Where(a => a.Id > (idtemp));
                  recipelist1 = searchCal.RecipesResultList(1, initgroupsize);

                }
                
            }
            ViewData["resultlist"] = recipelist1;
            ViewData["groupnumber"] = groupnumber;
            return View();
        } 
        public ActionResult Search(string category, string searchPattern)
        {
            var groupnumberlist = new SelectList(new[] { "6", "12", "24" });
            ViewBag.GroupNumberList = groupnumberlist;
            var searchlist = new SelectList(new[] { "Title", "Food Rate", "people number" });
            ViewBag.SearchList = searchlist;
            if (searchPattern.IsEmpty())
            {
                ModelState.AddModelError("searchPattern", "Shouldn't be empty");
            }
            if (ModelState.IsValid)
            {
                var db = new RecipeDataContext();
                IQueryable<Recipe> results = db.Recipes;
                
                if (category == "Food Rate")
                {
                    results = results.Where(a => a.FinalRate >= double.Parse(searchPattern));
                }
                else  if(category=="People Number")
                {
                    int i = int.Parse(searchPattern);
                    results = results.Where(recipe => recipe.PeopoleNumber == i);
                }
                else
                {
                    results = results.Where(recipe => recipe.Title.Contains(searchPattern));
                }
            
                //return View("Search", results);
                ViewData["resultlist"] = results;

            }
            return View();
        }

        public ActionResult RecipeDetails(long? id)
        {
          
            Debug.WriteLine(WebSecurity.CurrentUserId);
            var db = new RecipeDataContext();
            if (!id.HasValue)
            {
                return RedirectToAction("Index");
            }


            
            var recipe = db.Recipes.Find(id);
           
                
            
            if (recipe == null)
            {
                return View(db.Recipes.FirstOrDefault());
              
            }
               var context = new UsersContext();
            var user = context.UserProfiles.SingleOrDefault(u => u.UserId==recipe.UserId);
            ViewBag.userName = user.NickName;
            return View(recipe);
            
        }
         [CustomAuthorizeAttribute]
        [HttpGet]
        public ActionResult Edit(long? id)
        {
            if (!id.HasValue)
            {
                return RedirectToAction("Index");
            }
            var db = new RecipeDataContext();
            var tempRecipe = db.Recipes.Find(id);
           // var tempRecipe = db.Recipes.FirstOrDefault();
            if (tempRecipe == null)
            {
                return RedirectToAction("Index");
               
            }
             var context = new UsersContext();
            var username = User.Identity.Name;
            var user = context.UserProfiles.SingleOrDefault(u => u.UserName == username);


            if (user.UserId == tempRecipe.UserId)
            {
                return RedirectToAction("RecipeDetails", new {id = id});
            }

           return View(tempRecipe);
        }
        [CustomAuthorizeAttribute]
        [HttpPost]
        public ActionResult Edit(Models.Recipe tempRecipe, HttpPostedFileBase file)
        {
            var db = new RecipeDataContext();
            var tempRecipeold = db.Recipes.Find(tempRecipe.Id);
            if (file != null && file.ContentLength > 0 && file.ContentType.StartsWith("image/"))
            {
                try
                {

                    string temppath = Guid.NewGuid() + Path.GetExtension(file.FileName);
                    string path = Path.Combine(Server.MapPath("~/Images/siteimg"), temppath);
                    int i;
                    file.SaveAs(path);
                    ViewBag.Message = "File uploaded successfully";
                    tempRecipe.ImgPath = Path.Combine("~/Images/siteimg", temppath);
                }
                catch (Exception ex)
                {
                    ViewBag.Message = "ERROR:" + ex.Message.ToString();
                }
            }
            
           
            tempRecipeold.TimeStamp = DateTime.Now;
            for (int i=0;i<tempRecipe.Ingredients.Count;i++  )
            {
                tempRecipeold.Ingredients[i].Name = tempRecipeold.Ingredients[i].Name;
                tempRecipeold.Ingredients[i].Amount = tempRecipeold.Ingredients[i].Amount;
                tempRecipeold.Ingredients[i].Unit = tempRecipeold.Ingredients[i].Unit;
            }
            tempRecipeold.Ingredients = tempRecipe.Ingredients;
            
            tempRecipe.RatingPeople = tempRecipeold.RatingPeople;
            if (ModelState.IsValid)
            {


               
                db.SaveChanges();
               
            }
            return RedirectToAction("RecipeDetails", new {id=tempRecipeold.Id});
        }

        [HttpPost]
        public ActionResult Rate(Rate rate)
        {

            var db = new RecipeDataContext();
            var i = rate.ReId;
            var tempRecipe = db.Recipes.Find(rate.ReId);
            if (rate.RateValue > 10 || rate.RateValue < 0)
            {
                ModelState.AddModelError("comm", "out of range");
            }
            else if (tempRecipe == null)
            {
                ModelState.AddModelError("ReId", "not found");
            }
            else
            {
                tempRecipe.Rates.Add(rate);
                tempRecipe.RatingPeople = tempRecipe.RatingPeople + 1;
                tempRecipe.FinalRate =(double)Math.Round(((tempRecipe.FinalRate*(tempRecipe.RatingPeople - 1) + rate.RateValue)/(tempRecipe.RatingPeople)), 2);

                db.SaveChanges();
            }
            if (!Request.IsAjaxRequest())
                return RedirectToAction("RecipeDetails", new {id = rate.ReId});


            return Json(new
            {
                FRate1 = tempRecipe.FinalRate,
                NNum = tempRecipe.RatingPeople

            });
        }

        [HttpPost]
        [ValidateAntiForgeryToken]

FoodRecipes/Controllers/ServicesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.UI.WebControls;
using System.Web.WebPages;
using FoodRecipes.Models;
using FoodRecipes.ProjectClasses;
using PagedList;

namespace FoodRecipes.Controllers
{
    public class ServicesController : Controller
    {
        private RecipeDataContext db = new RecipeDataContext();

        //
        // GET: /Services/
        //[HttpGet]
        //public ViewResult SortView()
        //{
        //    StaticInfo saticinfo = new StaticInfo(db);
        //    var groupnumberlist = new SelectList(new[] { "6", "12", "24" });
        //    ViewBag.GroupNumberList = groupnumberlist;
        //    var sortOrderlist = new SelectList(new[] { "Rate", "Name", "Date", "CookingTime" });
        //    ViewBag.sortOrderlist = sortOrderlist;
        //    var sortOrder = "FinalRate";
        //    var recipestemp = saticinfo.SortRecipes(sortOrder, db);
        //    var pageNumber = 1;
        //    var pageSize =  6;

        //    return View(recipestemp.ToPagedList(pageNumber, pageSize));
        //}
        //[HttpPost]
        public ViewResult SortView(string sortOrder, int? page, int? pagesize,bool ? cookingTimeActive,string cookingTime)
        {
            StaticInfo saticinfo = new StaticInfo(db);
            var groupnumberlist = new SelectList(new[] { "6", "12", "24" });
            ViewBag.GroupNumberList = groupnumberlist;
            var sortOrderlist = new SelectList(new[] {  "Rate","Name", "Date", "CookingTime" });
            ViewBag.sortOrderlist = sortOrderlist;
            
          
            if (sortOrder.IsEmpty())
            {
                sortOrder = "FinalRate";
            }
            var recipestemp = saticinfo.SortRecipes(sortOrder, db);
            
            if (cookingTimeActive==true)
            {
                var intcotime = int.Parse(cookingTime);
                //recipestemp = saticinfo.CookingTimeLess(intcotime, recipestemp);
                recipestemp = from item in recipestemp
                              where item.CookingTime <= intcotime
                              select item;
            }

            //if (!pNumberState.IsEmpty())
            //{
            //    var intPnum = int.Parse(peopleNum);
            //    if (pNumberState.Equals("less"))
            //    {
            //        recipestemp = from item in recipestemp
            //            where item.PeopoleNumber <= intPnum
            //            select item;
            //    }
            //    else
            //    {
            //        recipestemp = from item in recipestemp
            //            where item.PeopoleNumber >= intPnum
            //            select item;
            //    }
            //}

            var pageNumber = (page ?? 1);
            var pageSize = (pagesize ?? 6);
           
            ViewBag.currentsize = pageSize;
            ViewBag.currentorder = sortOrder;
            //return HttpUtility.HtmlEncode("pageSize" + pageSize+ ",pageNimber" + pageNumber);
            return  View(recipestemp.ToPagedList(pageNumber, pageSize));
        }

        





        // GET: /Services/Delete/5

        public ActionResult Delete(long id = 0)
        {
            Recipe recipe = db.Recipes.Find(id);
            if (recipe == null)
            {
                return HttpNotFound();
            }
            return View(recipe);
        }

        //
        // POST: /Services/Delete/5

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(long id)
        {
            Recipe recipe = db.Recipes.Find(id);
            db.Recipes.Remove(recipe);
            db.SaveChanges();
            return RedirectToAction("SortView");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

FoodRecipes/Views/Services/Delete.cshtml
@model FoodRecipes.Models.Recipe

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<fieldset>
    <legend>Recipe</legend>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Title)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Title)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.TimeStamp)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.TimeStamp)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.CookingTime)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.CookingTime)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.PeopoleNumber)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.PeopoleNumber)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.ImgPath)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.ImgPath)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.FoodPreparation)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.FoodPreparation)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.FinalRate)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.FinalRate)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.RatingPeople)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.RatingPeople)
    </div>
</fieldset>
@using (Html.BeginForm()) {
    <p>
        <input type="submit" value="Delete" /> |
        @Html.ActionLink("Back to List", "Index")
    </p>
}

FoodRecipes/Views/Services/SortView.cshtml
@model PagedList.IPagedList<FoodRecipes.Models.Recipe>
@using PagedList.Mvc;
<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />
@{
    ViewBag.Title = "SortView";
   
}

<h2>SortView</h2>
<h2> @Html.ActionLink("Back to search", "Search", "Recipe")</h2>


<div class="container">
   
    <div class="row" style="margin-top: 3em">
   
        <aside class="col-lg-3 col-md-4 searchaside" style="border: 1px solid ;margin-left: -5em">
            @*@using (Html.BeginForm("SortView", "Services", new { pageNumber = Model.PageNumber}))*@
            @using (Html.BeginForm())
            {
                <fieldset>
                    
                   
                    <div class="editor-label">
                        @Html.Label("page size:")
                    </div>
                    <div class= "editor-field">
                        @Html.DropDownList("pagesize", (SelectList)ViewBag.GroupNumberList)
                   
                        @Html.ValidationMessage("pagesize")
                    </div>
                    <div class="editor-label">
                        @Html.Label("Sort Patrn:")
                    </div>

                    <div class="editor-field">
                        @Html.DropDownList("sortOrder", (SelectList)ViewBag.sortOrderlist)
                    </div>
                    @Html.Hidden("Page", 1)
                    <hr/>
                    <div>
                        
                        <label>
                            
                            @* @Html.CheckBox("cotimeActive", new { id = "cotimeActive1" })*@
                             <input type="checkbox" name="cotimeActive" value="false" id = "cotimeActive1" >
                            Cooking Time less than
                        </label>
                        <div >
                            @Html.TextBox("coTime",0, new { size = 3, id = "coTime1" }) min
                            </div>
                    </div>
                    <div >
                        <p>
                            @Html.RadioButton("PNumberState", "less", false)Recipe For less than
                        </p>
                        <p>
                            @Html.RadioButton("PNumberState", "more", true)Recipe For more than
                        </p>
                        <p>
                            @Html.TextBox("Pnum", 0, new { size = 3 })People
                        </p>
                    </div>
                 
                    
                    <p>
                      
                        <input type="submit" class="btn btn-danger" value="Refresh"id="sendForm"  />
                    </p>
                         
                </fieldset>
            }
        </aside>


        <article class="searchPartialView col-lg-9 col-md-8" style="border: 2px solid;margin-left: 5em">
          
         
            @foreach (var item in Model)
            {
                <div class="col-lg-3 col-sm-4 thumbnail"  >
                    @{
                        string pa = item.ImgPath;
                    }
                    <img src="@Url.Content(pa)" class="img-responsive"alt="" >
                    <p style="text-align: center">@item.Title</p>
                    
                    
                    @Html.ActionLink("see more..", "RecipeDetails", "Recipe", new { id = item.Id }, null)
                  
                </div>
            }

        
        </article>

        

    </div>
    <div class="row">
        <div class="col-lg-8 col-lg-push-3" >
            <div class="row">
            
                <div class="col-lg-2"style="margin-top: 0.4em">
                    Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount  
                </div>
                <div class="col-lg-6" style="margin-top: -1em">
                    @Html.PagedListPager(Model, page => Url.Action("SortView", new { page, ViewBag.currentorder, ViewBag.currentsize })) 
                    
                
                </div>
            </div>
        </div>

    </div>
   
</div>



@* ReSharper disable once WrongExpressionStatement *@

<script type="text/javascript">
    document.querySelector("#sendForm").addEventListener('click', function(e) {
        console.log(e.target);
        e.preventDefault();
        //var form = $(this).parent("form");


//    var url = "Services/SortView/##pageNumber/##pageSize";

        var url = "@Html.Raw(Url.Action("SortView", "Services", new { pageNumber = Model.PageNumber, sortOrder = "__sortOrder", pageSize = "__pageSize", cookingTimeActive = "__coTimeActive", cookingTime = "__cookingTime"}))";
        //int? page, //string Pnum
        console.log(e.target);
        url = url.replace("__pageSize", $('#pagesize').val());
        url = url.replace("__sortOrder", $('#sortOrder').val());
        url = url.replace("__coTimeActive",$('#cotimeActive1').is(':checked'));
        //$('#cotimeActive1').val() );
        url = url.replace("__cookingTime", $('#coTime1').val());
        // url=url.replace("__pNumberState",$('#PNumberState').val() );
        // url=url.replace("__peopleNum",$('#Pnum').val() );


        window.location = url;
        console.log(url);
    });

</script>